a, b, x, y = map(int, input("Enter a, b, x and y respectively - ").split())
c = (a * x)
d = (b * y)
total = (c + d)
# print(c, d)
print ("Chief has to pay %d units for Pens and %d units for Pencils" %(c,d))
print ("Total amount Chef will spend to buy a pens and b pencils is %d" %(total))